// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ao4KeL_7c6eWjQhrnvb95pjGAPSvCxQ',
    appId: '1:228761486242:web:10e4b8d67964cb04a628fb',
    messagingSenderId: '228761486242',
    projectId: 'let-sgo-31395',
    authDomain: 'let-sgo-31395.firebaseapp.com',
    storageBucket: 'let-sgo-31395.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8JMg9ykYN4CrN3idqCcLvTh9w2Ov-GxY',
    appId: '1:228761486242:android:4e01e45b2aa43a70a628fb',
    messagingSenderId: '228761486242',
    projectId: 'let-sgo-31395',
    storageBucket: 'let-sgo-31395.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4WATUbGSm4DF74Z6k4YT4-07kfEbFFh4',
    appId: '1:228761486242:ios:16b97949c4dff437a628fb',
    messagingSenderId: '228761486242',
    projectId: 'let-sgo-31395',
    storageBucket: 'let-sgo-31395.appspot.com',
    iosBundleId: 'com.example.letsGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4WATUbGSm4DF74Z6k4YT4-07kfEbFFh4',
    appId: '1:228761486242:ios:16b97949c4dff437a628fb',
    messagingSenderId: '228761486242',
    projectId: 'let-sgo-31395',
    storageBucket: 'let-sgo-31395.appspot.com',
    iosBundleId: 'com.example.letsGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2ao4KeL_7c6eWjQhrnvb95pjGAPSvCxQ',
    appId: '1:228761486242:web:bcbf91667f12728ea628fb',
    messagingSenderId: '228761486242',
    projectId: 'let-sgo-31395',
    authDomain: 'let-sgo-31395.firebaseapp.com',
    storageBucket: 'let-sgo-31395.appspot.com',
  );
}
